name: Publish to GH Pages
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
    publish-pages:
      name: Publish to GH Pages
      runs-on: ubuntu-latest
      steps:
          - name: Checkout Source Code
            uses: actions/checkout@v2
          - name: Checkout GH Pages
            uses: actions/checkout@v2
            with:
              repository: krauhen/fRAGme.github.io
              fetch-depth: 0
              path: "docs/_build"
              token: ${{ secrets.PUSH_DOCS_TOKEN }}
          - name: Build Docs
            uses: krauhen/sphinx-action@master
            with:
              docs-folder: "docs/"
              pre-build-command: "pip3 install ."
              build-command: "sphinx-build -b html . _build -W"
          - name: Push Changes
            uses: ad-m/github-push-action@master
            with:
              github_token: ${{ secrets.PUSH_DOCS_TOKEN }}
              directory: docs/_build
              repository: krauhen/fRAGme.github.io
              force: true
              tags: true
