name: Publish Documentation

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.6'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install .[dev]
        pip install -r docs/requirements.txt

    - name: Build documentation
      run: sphinx-build docs docs/_build/ -W --keep-going --write-all

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository: krauhen/fRAGme.github.io
        publish_dir: docs/_build
        publish_branch: gh-pages
